list: $/app06/juniortestplugin/models/product/columns.yaml
modelClass: App06\Juniortestplugin\Models\Product
title: Products
noRecordsMessage: 'backend::lang.list.no_records'
showSetup: true
showCheckboxes: true
recordsPerPage: 20
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
recordUrl: 'app06/juniortestplugin/products/update/:id'
