name: Categories
form: $/app06/juniortestplugin/models/category/fields.yaml
modelClass: App06\Juniortestplugin\Models\Category
defaultRedirect: app06/juniortestplugin/categories
create:
    redirect: 'app06/juniortestplugin/categories/update/:id'
    redirectClose: app06/juniortestplugin/categories
update:
    redirect: app06/juniortestplugin/categories
    redirectClose: app06/juniortestplugin/categories
